/** Whether an admin user is already configured. */
export interface AuthStatus {
  configured: boolean;
}

/** Result of the first-run admin setup (used by the CLI). */
export interface AuthSetupResult {
  configured: boolean;
  /**
   * The admin password when the server generated one (shown once on screen).
   * Null when the caller supplied their own password.
   */
  password: string | null;
  /** True when the password was auto-generated by the server. */
  generated: boolean;
}

/** Result of a successful login. */
export interface AuthLoginResult {
  /**
   * The admin bearer token. Present only when the device is already validated.
   * When the device is new/pending, `devicePending` is true instead and no
   * token is issued until the device is approved from the host terminal.
   */
  token?: string;
  /** True when the device is new/pending and must be approved via the CLI. */
  devicePending?: boolean;
  /** The device id (stored in the device cookie). */
  deviceId?: string;
  /** The 6-char approval code shown to the user. */
  code?: string;
}

/** Result of resetting the admin password. */
export interface AuthResetResult {
  /** The new password (shown once on screen). */
  password: string;
  generated: boolean;
}

/** A device (browser/agent) associated with a user. */
export interface DeviceDto {
  id: number;
  deviceId: string;
  name: string;
  status: 'pending' | 'validated' | 'revoked';
  createdAt: string;
  lastAttemptAt: string | null;
  lastLoginAt: string | null;
  isCurrent?: boolean;
}

/** Result of changing the admin password. */
export interface ChangePasswordResult {
  ok: boolean;
}
