#!/usr/bin/env bash
set -euo pipefail

# Temporary migration helper:
# Import current runtime-related values from .env to var/config.toml.
#
# Usage:
#   scripts/temp_import.sh [ENV_FILE] [OUT_FILE]
#
# Defaults:
#   ENV_FILE = ./.env
#   OUT_FILE = ./var/config.toml

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"
ENV_FILE="${1:-$ROOT_DIR/.env}"
OUT_FILE="${2:-$ROOT_DIR/var/config.toml}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[temp_import] Missing env file: $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

mkdir -p "$(dirname -- "$OUT_FILE")"

trim() {
  local v="$1"
  # strip leading/trailing whitespace
  v="${v#"${v%%[![:space:]]*}"}"
  v="${v%"${v##*[![:space:]]}"}"
  printf '%s' "$v"
}

toml_escape() {
  local v="$1"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  printf '%s' "$v"
}

# Defaults aligned with current runtime behavior.
CODEPODS_ROOT_PATH="$(trim "${CODEPODS_ROOT_PATH:-$ROOT_DIR}")"
CODEPODS_DB_PATH="$(trim "${CODEPODS_DB_PATH:-$CODEPODS_ROOT_PATH/var/codepods.db}")"
CODEPODS_TEMPLATES_PATH="$(trim "${CODEPODS_TEMPLATES_PATH:-${CODEPODS_AGENT_TYPES_PATH:-$CODEPODS_ROOT_PATH/templates}}")"
CODEPODS_DATA_DIR="$(trim "${CODEPODS_DATA_DIR:-$CODEPODS_ROOT_PATH/var/data}")"
CODEPODS_TMP_RENDER_DIR="$(trim "${CODEPODS_TMP_RENDER_DIR:-$CODEPODS_ROOT_PATH/var/tmp/codepods}")"

AUTH_REQUIRE_APPROVED_DEVICE="$(trim "${AUTH_REQUIRE_APPROVED_DEVICE:-true}")"
SESSION_LIFETIME="$(trim "${SESSION_LIFETIME:-86400}")"

RELAY_PORT_MIN="$(trim "${RELAY_PORT_MIN:-10000}")"
RELAY_PORT_MAX="$(trim "${RELAY_PORT_MAX:-10100}")"
RELAY_TOKEN_LIFETIME="$(trim "${RELAY_TOKEN_LIFETIME:-120}")"
RELAY_COOKIE_LIFETIME="$(trim "${RELAY_COOKIE_LIFETIME:-14400}")"
RELAY_SESSION_COOKIE="$(trim "${RELAY_SESSION_COOKIE:-relay_session}")"

PUBLIC_DOMAIN="$(trim "${PUBLIC_DOMAIN:-}")"
WEB_BASE_URL="$(trim "${WEB_BASE_URL:-}")"
CODEPODS_SWAGGER_ENABLED="$(trim "${CODEPODS_SWAGGER_ENABLED:-true}")"
CORS_ORIGINS="$(trim "${CORS_ORIGINS:-}")"
TLS_CERT_PATH="$(trim "${TLS_CERT_PATH:-}")"
TLS_KEY_PATH="$(trim "${TLS_KEY_PATH:-}")"
CERTBOT_EMAIL="$(trim "${CERTBOT_EMAIL:-}")"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/temp_import.sh
# IMPORTANT:
# - This imports runtime config values from .env.
# - Secrets are intentionally NOT copied from env (SESSION_SECRET, DEVICE_SECRET, API keys, etc.).
# - Agent template/render variables are intentionally excluded from this file.

[app]
root_path = "$(toml_escape "$CODEPODS_ROOT_PATH")"
templates_path = "$(toml_escape "$CODEPODS_TEMPLATES_PATH")"
data_dir = "$(toml_escape "$CODEPODS_DATA_DIR")"
tmp_render_dir = "$(toml_escape "$CODEPODS_TMP_RENDER_DIR")"

[db]
sqlite_path = "$(toml_escape "$CODEPODS_DB_PATH")"

[auth]
require_approved_device = ${AUTH_REQUIRE_APPROVED_DEVICE,,}
session_lifetime = $SESSION_LIFETIME

[relay]
port_min = $RELAY_PORT_MIN
port_max = $RELAY_PORT_MAX
token_lifetime = $RELAY_TOKEN_LIFETIME
cookie_lifetime = $RELAY_COOKIE_LIFETIME
cookie_name = "$(toml_escape "$RELAY_SESSION_COOKIE")"

[web]
swagger_enabled = ${CODEPODS_SWAGGER_ENABLED,,}
EOF

if [[ -n "$PUBLIC_DOMAIN" ]]; then
  printf 'public_domain = "%s"\n' "$(toml_escape "$PUBLIC_DOMAIN")" >> "$OUT_FILE"
fi
if [[ -n "$WEB_BASE_URL" ]]; then
  printf 'base_url = "%s"\n' "$(toml_escape "$WEB_BASE_URL")" >> "$OUT_FILE"
fi
if [[ -n "$CORS_ORIGINS" ]]; then
  printf 'cors_origins = "%s"\n' "$(toml_escape "$CORS_ORIGINS")" >> "$OUT_FILE"
fi

cat >> "$OUT_FILE" <<EOF

[tls]
EOF

if [[ -n "$TLS_CERT_PATH" ]]; then
  printf 'cert_path = "%s"\n' "$(toml_escape "$TLS_CERT_PATH")" >> "$OUT_FILE"
fi
if [[ -n "$TLS_KEY_PATH" ]]; then
  printf 'key_path = "%s"\n' "$(toml_escape "$TLS_KEY_PATH")" >> "$OUT_FILE"
fi
if [[ -n "$CERTBOT_EMAIL" ]]; then
  printf 'certbot_email = "%s"\n' "$(toml_escape "$CERTBOT_EMAIL")" >> "$OUT_FILE"
fi

cat >> "$OUT_FILE" <<'EOF'

[keys]
# If omitted, runtime should generate and use local key files under var/keys.
# master_key_path = "var/keys/master.key"
EOF

echo "[temp_import] Imported runtime values from: $ENV_FILE"
echo "[temp_import] Wrote config: $OUT_FILE"
